debug = true

defaultEntryPoints = ["http"]

# Activate docker API
[docker]
# swarmMode = true
# exposedByDefault = false
endpoint = "unix:///var/run/docker.sock"
domain = "docker.local"
watch = true

# Activate Traefik dashboard
[api]
  dashboard=true